import { FileTreeItemModel } from '../../shared/models/file-tree-item.model';

export const seededData: FileTreeItemModel[] = [
  {
    name: 'HelloWorldFolder',
    path: 'home/HelloWorldFolder',
    type: 'folder',
    expanded: false,
    children: [
      {
        name: 'WeAreFrankFolder',
        path: 'home/HelloWorldFolder/WeAreFrankFolder',
        type: 'folder',
        expanded: false,
        children: [
          {
            name: 'FrankConfig',
            path: 'home/HelloWorldFolder/WeAreFrankFolder/FrankConfig.xml',
            type: 'file',
            xml: '<Frank>WeAreFrank!</Frank>',
            fileType: 'configuration',
            flowNeedsUpdate: false,
            firstLoad: false,
            saved: true,
            extension: 'xml',
            flowStructures: ['Adapter1', 'Adapter2'],
          },
          {
            name: 'SergiConfig',
            path: 'home/HelloWorldFolder/WeAreFrankFolder/SergiConfig.xml',
            type: 'file',
            xml: '<Frank>Wizard Sergi!</Frank>',
            fileType: 'configuration',
            flowNeedsUpdate: false,
            firstLoad: false,
            saved: true,
            extension: 'xml',
            flowStructures: ['Adapter1', 'Adapter2'],
          },
        ],
      },
      {
        name: 'HelloWorldConfiguration',
        path: 'home/HelloWorldFolder/HelloWorldConfiguration',
        type: 'file',
        extension: 'xml',
        fileType: 'configuration',
        flowNeedsUpdate: true,
        xml: '<test>Test</test>',
        saved: true,
        firstLoad: false,
        flowStructures: ['Adapter1', 'Adapter2'],
      },
      {
        name: 'helloworld',
        path: 'home/HelloWorldFolder/helloworld.txt',
        type: 'file',
        extension: 'txt',
        saved: true,
        firstLoad: false,
        fileType: 'other',
      },
    ],
  },
  {
    name: 'GoodByeWorld',
    path: 'home/GoodByeWorld.xml',
    type: 'file',
    extension: 'xml',
    saved: true,
    firstLoad: false,
    fileType: 'configuration',
    flowNeedsUpdate: false,
    xml: '<Test>Test1234</Test>',
    flowStructures: ['Adapter1', 'Adapter2'],
  },
];
