version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    labels:
      - "dependencies"
      - "java"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/frank-flow/src/frontend/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
      - "automerge"
    commit-message:
      prefix: "build"
      include: "scope"

