version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frank-flow/src/frontend/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
      - "automerge"
