version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    labels:
      - "dependencies"
      - "java"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(dependencies):"
      prefix-development: "chore(devDependencies):"
      include: "scope"
  - package-ecosystem: "maven"
    directory: "/frank-flow/"
    labels:
      - "dependencies"
      - "java"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(dependencies):"
      prefix-development: "chore(devDependencies):"
      include: "scope"
  - package-ecosystem: "maven"
    directory: "/frank-flow-launcher/"
    labels:
      - "dependencies"
      - "java"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(dependencies):"
      prefix-development: "chore(devDependencies):"
      include: "scope"
  - package-ecosystem: "maven"
    directory: "/frank-flow-webapp/"
    labels:
      - "dependencies"
      - "java"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(dependencies):"
      prefix-development: "chore(devDependencies):"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/frank-flow/src/frontend/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
      - "automerge"
    commit-message:
      prefix: "fix(dependencies):"
      prefix-development: "chore(devDependencies):"
      include: "scope"

