version = 1

[merge]
automerge_label = "automerge"
method = "rebase"
delete_branch_on_merge = true
notify_on_conflict = false

[approve]
auto_approve_usernames = ["dependabot"]

[update]
always = true
ignored_usernames = ["dependabot"]
