version = 1

[merge]
automerge_label = "automerge"
method = "squash"
delete_branch_on_merge = true

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]

[update]
always = true
ignored_usernames = ["dependabot"]
