version: "3"

services:
  frank:
    image: frank-flow
    build: .
    ports:
      - "8080:8080"
    environment:
      - dtap.stage=LOC
      - instance.name=Frank2FrankFlow
      - database.instance.name=frank2frankflow
      - database.name=database
    restart: unless-stopped
