name: Angular CI

on: push
#  push:
#    branches:
#      - master
#    paths:
#      - "frank-flow/src/frontend/**"
#  pull_request:
#      branches:
#        - master
#      paths:
#        - "frank-flow/src/frontend/**"

jobs:
  cypress-test:
    runs-on: self-hosted
    steps:
      - name: Checkout frank-flow repository
        uses: actions/checkout@v2
        with:
          path: frank-flow
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Checkout frank-runner
        uses: actions/checkout@v2
        with:
          repository: ibissource/frank-runner
          path: frank-runner
      - name: Working directory
        run: pwd
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        working-directory: frank-flow/frank-flow/src/frontend
        run: npm ci
      - name: Run unit tests
        working-directory: frank-flow/frank-flow/src/frontend
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: Write frank-flow.properties
        run: echo "frank-flow.frontend-path = $(pwd)/frank-flow/frank-flow/target/frontend" > frank-runner/frank-flow.properties
      - name: Build backend
        run: mvn -f frank-flow -P frontend clean install
      - name: Cache Frank!Runner downloads and builds
        uses: actions/cache@v2
        env:
          cache-name: cache-frank-runner
        with:
          path: |
            frank-runner/build
            frank-runner/downloads
          key: ${{ runner.os }}-frank-runner-${{ hashFiles('**/ibis-adapterframework-webapp-*') }}
          restore-keys: |
            ${{ runner.os }}-frank-runner-
      - name: Start Frank!Runner
        working-directory: frank-flow/frank-flow/src/frontend/cypress/Frank
        run: ./restart.sh
      - name: Run cypress
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: frank-flow/frank-flow/src/frontend
#      - name: List all files
#        if: always()
#        run: tree > allFiles.txt
#      - name: Store (logging) information as artifact
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: logs
#          path: |
#            allFiles.txt
#            backendMavenBuildLog.txt
#            frank-runner\\build.properties
#            frank-runner\\frank-flow.properties
#            frank-runner\\build\\apache-tomcat*\\logs
#            frank-flow\\frank-flow\\src\\frontend\\cypress\\screenshots
