name: Angular CI

on: push
#  push:
#    branches:
#      - master
#    paths:
#      - "frank-flow/src/frontend/**"
#  pull_request:
#      branches:
#        - master
#      paths:
#        - "frank-flow/src/frontend/**"

jobs:
  cypress-test:
    runs-on: self-hosted
    steps:
      - name: Checkout frank-flow repository
        uses: actions/checkout@v2
        with:
          path: frank-flow
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Checkout frank-runner
        uses: actions/checkout@v2
        with:
          repository: ibissource/frank-runner
          path: frank-runner
      - name: Working directory
        run: pwd
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      #      - name: Cache npm dependencies
      #        uses: actions/cache@v2
      #        with:
      #          path: "~/.npm"
      #          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #          restore-keys: |
      #            ${{ runner.os }}-node-
      #      - name: Install npm dependencies
      #        working-directory: frank-flow/frank-flow/src/frontend
      #        run: npm install
      #      - name: Run unit tests
      #        working-directory: frank-flow/frank-flow/src/frontend
      #      #        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      #      - name: Write frank-flow.properties
      #        run: echo "frank-flow.frontend-path = $(pwd)/frank-flow/frank-flow/target/frontend" > frank-runner/frank-flow.properties
      - name: Build backend
        run: mvn -f frank-flow -P frontend
      - name: Cache Frank!Runner dependencies
        uses: actions/cache@v2
        with:
          path: |
            frank-runner/build
            frank-runner/download
          key: ${{ runner.os }}-frank-runner
          restore-keys: |
            ${{ runner.os }}-frank-runner
      #      - name: Start Frank!Runner
      #        working-directory: frank-flow/frank-flow/src/frontend/cypress/Frank
      #        run: ./restart.sh
      - name: Run cypress using the Frank!Runner
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: frank-flow/frank-flow/src/frontend/
          #          build: npm run build
          start: npm run runner
          wait-on: "http://localhost:1000/frank-flow/"
          wait-on-timeout: 450
#      - name: List all files
#        if: always()
#        run: tree > allFiles.txt
#      - name: Store (logging) information as artifact
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: logs
#          path: |
#            allFiles.txt
#            backendMavenBuildLog.txt
#            frank-runner\\build.properties
#            frank-runner\\frank-flow.properties
#            frank-runner\\build\\apache-tomcat*\\logs
#            frank-flow\\frank-flow\\src\\frontend\\cypress\\screenshots
