name: End to End Testing (Docker)

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

jobs:
  e2e-docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout frank-flow repository
        uses: actions/checkout@v4
      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build the backend
        run: mvn install -P frankframework,ci

      - name: Cache local Maven repository
        uses: actions/cache@v4
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Cypress using the frank-framework Docker image
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend/src/main/frontend/
          build: npm run build:prod
          start: docker-compose up -d
          wait-on: "http://localhost:8080/"
          wait-on-timeout: 360
