name: Semantic Release

on:
  workflow_run:
    branches: [ "master" ]
    workflows: [ "Frontend CI" ]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout frank-flow repository
        uses: actions/checkout@v2
        with:
          path: frank-flow
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install semantic-release
        run: yarn global add @conveyal/maven-semantic-release semantic-release
      - name: Run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release --skip-maven-deploy