name: Semantic Release

on:
  workflow_run:
    branches: [ "master" ]
    workflows: [ "Frontend CI" ]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout frank-flow repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          path: frank-flow
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn global add semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec conventional-changelog-metahub
      - name: Run semantic release
        working-directory: frank-flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: chmod +x ./prepare-release.sh && semantic-release