name: Semantic Release

on:
  workflow_run:
    branches: [ "master" ]
    workflows: [ "Frontend CI" ]
    types:
      - completed

defaults:
  run:
    working-directory: frank-flow/frank-flow/src/frontend

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout frank-flow repository
        uses: actions/checkout@v2
        with:
          path: frank-flow
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn
      - name: Run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release